# Even though we run everything inside docker Travis require
# us to pick a language else it will pick Ruby by default
# language: generic
# language: ruby

# Choose a lightweight base image; we provide our own build tools.
# https://github.com/lukasmartinelli/hadolint/blob/master/.travis.yml#L1
language: c

# Omit running tests on temporal branches,
#  i.e. branches with names that start with "tmp"
branches:
  except:
    - /^tmp/

env:
  global:
    - TEST_SLEEPS="0.7"
    - ADDED_TEST_SLEEP="6.5"

# sudo: required
# dist: trusty
# services:
#   - docker

matrix:
  allow_failures:
    # Currently erroring in Mac (OSX):
    #  https://travis-ci.org/elgalu/docker-selenium/jobs/143553463#L636
    #   com.docker.docker Incompatible CPU detected
    #   Docker requires a processor with virtualization capabilities
    - env:
        - DOCKER_VERSION="stable"
          DOCKER_COMPOSE_VERSION="stable"
          OPERATING_SYSTEM="osx"
  include:
    # Linux with docker:stable compose:stable
    # Use DOCKER_PUSH_LATEST=false to debug
    - os: linux
      language: c
      sudo: required
      dist: trusty
      services:
        - docker
      env:
        - DOCKER_VERSION="stable"
          DOCKER_COMPOSE_VERSION="1.8.1"
          DOCKER_PUSH=true
          DOCKER_PUSH_LATEST=true
    # Linux with docker:beta/older compose:beta/older
    - os: linux
      language: c
      sudo: required
      dist: trusty
      services:
        - docker
      env:
        - DOCKER_VERSION="1.12.1"
          DOCKER_COMPOSE_VERSION="1.8.1"
    # Linux with docker:stable compose:beta/older
    - os: linux
      language: c
      sudo: required
      dist: trusty
      services:
        - docker
      env:
        - DOCKER_VERSION="stable"
          DOCKER_COMPOSE_VERSION="1.8.0"
    # Linux with docker:beta/older compose:stable
    - os: linux
      language: c
      sudo: required
      dist: trusty
      services:
        - docker
      env:
        - DOCKER_VERSION="1.12.1"
          DOCKER_COMPOSE_VERSION="1.8.0"
    # Mac OSX: only test native docker version
    - os: osx
      osx_image: xcode8
      env:
        - DOCKER_VERSION="stable"
          DOCKER_COMPOSE_VERSION="stable"
          OPERATING_SYSTEM="osx"

before_install:
  - travis_retry ./test/before_install_setup
  - travis_retry ./test/before_install_build

install:
  - ./test/install

script:
  - ./test/script_start
  - travis_retry ./test/script_scenario_make
  - travis_retry ./test/script_scenario_compose_1_1
  - travis_retry ./test/script_scenario_compose_N_N
  - ./test/script_end

# cleanup though doesn't seem to be necessary in Travis infra
after_script:
  - ./test/after_script
